language: node_js

node_js:
  - stable

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm run lint
  - npm test

after_script:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info

notifications:
  email: false
