language: node_js
node_js:
- stable
env:
  matrix:
  - TRAVIS=true
  global:
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- yarn global add yarn@latest codecov && source ~/.bashrc
script:
- yarn build
- yarn test
after_script:
- codecov
notifications:
  email: false