devenv_container: &devenv_container
  image: containers.caseywebb.xyz/profiscience/knockout-contrib
  pull: true

kind: pipeline
name: default

image_pull_secrets:
  - DOCKER_CONFIG_JSON

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head

steps:
  - name: environment
    image: plugins/docker
    when:
      branch:
        - master
    settings:
      repo: containers.caseywebb.xyz/profiscience/knockout-contrib
      registry: containers.caseywebb.xyz
      cache_from: containers.caseywebb.xyz/profiscience/knockout-contrib
      username: profiscience-buildbot
      password:
        from_secret: DOCKER_REGISTRY_PASSWORD

  - name: dependencies
    <<: *devenv_container
    depends_on:
      - environment
    commands:
      - yarn install

  - name: lint
    <<: *devenv_container
    depends_on:
      - dependencies
    commands:
      - yarn lint

  - name: build
    <<: *devenv_container
    depends_on:
      - dependencies
    commands:
      - yarn build

  - name: test:jest
    <<: *devenv_container
    depends_on:
      - dependencies
      - build
    commands:
      - yarn test

  - name: test:karma
    <<: *devenv_container
    depends_on:
      - dependencies
      - build
    commands:
      - source ./support/xvfb_entrypoint.sh
      - yarn test:router

  - name: report:coverage
    <<: *devenv_container
    depends_on:
      - test:jest
      - test:karma
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
    commands:
      - npx codecov -t $CODECOV_TOKEN

---
kind: secret
name: CODECOV_TOKEN
data: sDltPEjpOCwZIQD0I3phbquSJLZ2rKvrUdnyLWH0TTRq7nk4dodP0NPdwGGdhfgSYZETIcisVzZg/mOKFkfm/A==

---
kind: secret
name: DOCKER_REGISTRY_PASSWORD
data: v6yir3VO2XionyT+YWoem5S+wym0os/nO4byNXkLILkmK7mWlc9sv1yEUBnxI/rlliSMCOk=
