---
devenv_container: &devenv_container
  image: containers.caseywebb.xyz/profiscience/knockout-contrib
  pull: true

when_master: &when_master
  when:
    ref:
      - refs/heads/master
    event:
      - push

kind: pipeline
name: default

image_pull_secrets:
  - DOCKER_CONFIG_JSON

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head

steps:
  - name: environment
    image: plugins/docker
    <<: *when_master
    settings:
      repo: containers.caseywebb.xyz/profiscience/knockout-contrib
      registry: containers.caseywebb.xyz
      cache_from: containers.caseywebb.xyz/profiscience/knockout-contrib
      username: profiscience-buildbot
      password:
        from_secret: DOCKER_REGISTRY_PASSWORD

  - name: dependencies
    <<: *devenv_container
    depends_on:
      - environment
    commands:
      - yarn install

  - name: lint
    <<: *devenv_container
    depends_on:
      - dependencies
    commands:
      - yarn lint

  - name: build
    <<: *devenv_container
    depends_on:
      - dependencies
    commands:
      - yarn build

  - name: test:jest
    <<: *devenv_container
    depends_on:
      - dependencies
      - build
    commands:
      - yarn test

  - name: test:karma
    <<: *devenv_container
    depends_on:
      - dependencies
      - build
    commands:
      - source ./support/xvfb_entrypoint.sh
      - yarn test:router

  - name: report:coverage
    <<: *devenv_container
    depends_on:
      - test:jest
      - test:karma
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
    commands:
      - npx codecov

  - name: publish:npm
    <<: *devenv_container
    <<: *when_master
    depends_on:
      - build
      - test:jest
      - test:karma
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - echo "//registry.npmjs.org/:_authToken=$${NPM_TOKEN}" >> .npmrc
      - npx lerna publish from-package --no-git-reset --yes

---
kind: secret
name: DOCKER_REGISTRY_PASSWORD
data: v6yir3VO2XionyT+YWoem5S+wym0os/nO4byNXkLILkmK7mWlc9sv1yEUBnxI/rlliSMCOk=

---
kind: secret
name: NPM_TOKEN
data: Jed1nG51yLt4bB+Vv1Zhu1M0a8h0LeUYwoiMG8RKwxH1KdfKot/RZnm5ewCTZdIm74gIfGO2bUWZAuf5gAV4cQ==

---
kind: signature
hmac: 99ac9a63fdaa929c86650c4153b49e46bbc383e530c1c661a0ebd6e44f338809
