kind: pipeline
name: default

steps:
  - name: Dependencies
    image: profiscience/knockout-contrib
    commands:
      - yarn install

  - name: Lint
    image: profiscience/knockout-contrib
    commands:
      - yarn lint

  - name: Build
    image: profiscience/knockout-contrib
    commands:
      - yarn build

  - name: Test
    image: profiscience/knockout-contrib
    commands:
      - yarn test
      - source ./support/xvfb_entrypoint.sh
      - yarn test:router
