dev_env: &dev_env
  image: plugins/docker
  settings:
    cache_from: profiscience/knockout-contrib

kind: pipeline
name: default

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head

steps:
  - name: dependencies
    <<: *dev_env
    commands:
      - yarn install

  - name: lint
    <<: *dev_env
    depends_on:
      - dependencies
    commands:
      - yarn lint

  - name: build
    <<: *dev_env
    depends_on:
      - dependencies
    commands:
      - yarn build

  - name: test:jest
    <<: *dev_env
    depends_on:
      - dependencies
      - build
    commands:
      - yarn test

  - name: test:karma
    <<: *dev_env
    depends_on:
      - dependencies
      - build
    commands:
      - source ./support/xvfb_entrypoint.sh
      - yarn test:router

  - name: report:coverage
    <<: *dev_env
    depends_on:
      - test:jest
      - test:karma
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
    commands:
      - npx codecov -t $CODECOV_TOKEN

---
kind: secret
name: CODECOV_TOKEN
data: sDltPEjpOCwZIQD0I3phbquSJLZ2rKvrUdnyLWH0TTRq7nk4dodP0NPdwGGdhfgSYZETIcisVzZg/mOKFkfm/A==
