kind: pipeline
name: default

trigger:
  branch:
    - master
  event:
    - push

trigger:
  event:
    - pull_request

steps:
  - name: dependencies
    image: profiscience/knockout-contrib
    commands:
      - yarn install

  - name: lint
    image: profiscience/knockout-contrib
    depends_on:
      - dependencies
    commands:
      - yarn lint

  - name: build
    image: profiscience/knockout-contrib
    depends_on:
      - dependencies
    commands:
      - yarn build

  - name: test
    image: profiscience/knockout-contrib
    depends_on:
      - dependencies
      - build
    commands:
      - yarn test
      - source ./support/xvfb_entrypoint.sh
      - yarn test:router