import * as fs from 'fs'
import * as path from 'path'
import { promisify as pify } from 'util'
import { camelCase } from 'lodash'
import chalk from 'chalk'

// tslint:disable no-var-requires
const { dependencies } = require(path.resolve(__dirname, '../package.json'))

const readdir = pify(fs.readdir)
const writeFile = pify(fs.writeFile)

const AUTOGEN_BANNER = `
/**
 * THIS IS AN AUTOGENERATED FILE
 */
`

async function getComponentPackages(): Promise<{ [k: string]: { name: string } }> {
  const prefix = 'components.'
  return (await readdir(path.resolve(__dirname, '../..')))
    .filter((d) => d.indexOf(prefix) === 0)
    .map((d) => d.replace(prefix, ''))
    .reduce((pkgs, name) => {
      const pkg = require(path.resolve(__dirname, `../../components.${name}/package.json`))
      if (!dependencies[pkg.name]) {
        // tslint:disable-next-line no-console max-line-length
        console.warn(chalk.yellow(`${name} component not listed as dependency of components metapackage. Did you forget to add it to components/package.json?`))
        return pkgs
      } else {
        return {
          ...pkgs,
          [name]: pkg
        }
      }
    }, {})
}

async function generateIndex(packages: { [k: string]: any }) {
  const names = Object.keys(packages)
  const contents = [
    AUTOGEN_BANNER,
    ...names.map((p) => `import './${p}'`)
  ].join('\n') + '\n'
  await writeFile(path.resolve(__dirname, '../index.ts'), contents)
}

async function generateLazyManifest(packages: { [k: string]: { name: string } }) {
  const names = Object.keys(packages)
  const contents = [
    AUTOGEN_BANNER,
    'import * as ko from \'knockout\'',
    'import { LazyComponentLoader } from \'./loader\'',
    'ko.components.loaders.unshift(new LazyComponentLoader({',
    ...names.map((n) => `  'contrib-${n}': () => import('${packages[n].name}') as any,`),
    '}))'
  ].join('\n') + '\n'
  await writeFile(path.resolve(__dirname, '../lazy.ts'), contents)
}

async function generateIndividual(name: string, pkg: { name: string }) {
  const contents = [
    AUTOGEN_BANNER,
    `import * as ko from 'knockout'\n`,
    `import componentConfig from '${pkg.name}'`,
    `export * from '${pkg.name}'`,
    `ko.components.register('contrib-${name}', componentConfig)`,
  ].join('\n') + '\n'
  await writeFile(path.resolve(__dirname, `../${name}.ts`), contents)
}

getComponentPackages()
  .then((packages) => Promise.all([
    generateIndex(packages),
    generateLazyManifest(packages),
    ...Object.keys(packages).map((k) => generateIndividual(k, packages[k]))
  ]))
  .catch((err) => {
    // tslint:disable-next-line no-console
    console.error('Error generating components metapackage', err.message)
    process.exit(1)
  })
