version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/repo

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./

  default:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build
      - run: yarn lint
      - run:
          environment:
            JEST_JUNIT_OUTPUT_DIR: test_output
            JEST_JUNIT_OUTPUT_NAME: jest.xml
          command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit
      - run: yarn test:router
      - codecov/upload:
          file: coverage/lcov.info
      - codecov/upload:
          file: packages/router/coverage/lcov.info
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./

  deploy:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo
      - run: npx lerna publish from-package --no-git-reset --yes

workflows:
  version: 2
  default:
    jobs:
      - dependencies
      - default:
          requires:
            - dependencies
      - deploy:
          requires:
            - default
          filters:
            branches:
              only: master
