version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo

jobs:
  dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node_modules-{{ .Branch }}-
            - node_modules-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./

  build:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./

  lint:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn lint

  test_unit:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          environment:
            JEST_JUNIT_OUTPUT_DIR: .test_output/jest
            JEST_JUNIT_OUTPUT_NAME: results.xml
          command: yarn test --maxWorkers 4 --reporters default --reporters jest-junit
      - store_test_results:
          path: .test_output/jest/results.xml

workflows:
  version: 2
  build_lint_test_publish:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
      - test_unit:
          requires:
            - build
