
/**
 * THIS IS AN AUTOGENERATED FILE
 */

import * as ko from 'knockout'

import ctrlClick from '@profiscience/knockout-contrib-bindings-ctrl-click'
export * from '@profiscience/knockout-contrib-bindings-ctrl-click'
ko.bindingHandlers.ctrlClick = ctrlClick
