
/**
 * THIS IS AN AUTOGENERATED FILE
 */

import * as ko from 'knockout'

import jquery from '@profiscience/knockout-contrib-bindings-jquery'
export * from '@profiscience/knockout-contrib-bindings-jquery'
ko.bindingHandlers.jquery = jquery
