
/**
 * THIS IS AN AUTOGENERATED FILE
 */

import * as ko from 'knockout'

import shiftClick from '@profiscience/knockout-contrib-bindings-shift-click'
export * from '@profiscience/knockout-contrib-bindings-shift-click'
ko.bindingHandlers.shiftClick = shiftClick
