
/**
 * THIS IS AN AUTOGENERATED FILE
 */

import * as ko from 'knockout'

import toggle from '@profiscience/knockout-contrib-bindings-toggle'
export * from '@profiscience/knockout-contrib-bindings-toggle'
ko.bindingHandlers.toggle = toggle
