language: node_js
node_js:
- stable
addons:
  firefox: latest
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run lint
- npm test
after_script:
- ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.txt
